# Note: currently you need to set the reference path manually. Look
# for folder data/genomes in your ngstestdata installation location
bwa:
  bwaref: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/bwa/chr11.fa

gatk:
  UnifiedGenotyper:
    ref: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/seq/chr11.fa

picard:
  # InputBamFile "pipes" input from other modules
  InputBamFile:
    parent_task: ratatosk.lib.tools.samtools.SamToBam
  HsMetrics:
    parent_task: ratatosk.lib.tools.picard.SortSam
    targets: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/seqcap/chr11_targets.interval_list
    baits: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/seqcap/chr11_baits.interval_list
  DuplicationMetrics:
    parent_task: ratatosk.lib.tools.picard.SortSam
  AlignmentMetrics:
    parent_task: ratatosk.lib.tools.picard.SortSam
  InsertMetrics:
    parent_task: ratatosk.lib.tools.picard.SortSam

samtools:
  SamToBam:
    parent_task: ratatosk.lib.align.bwa.BwaSampe

pipeline:
  HaloPlex:
    target_generator_function: ratatosk.ext.scilife.sample.target_generator
